title: lkslawek's blog
theme: minima
titles_from_headings:
  collections: true
  strip_title: true
google_analytics: UA-196241499-1
disqus:
  shortname: lkslawek
show_excerpts: true
github_username: lkslawek
header_pages:
  - null
